### ISSUE TITLE
Nvidia: Extract 32bit libs from 64bit installer

### ISSUE THREAD

**Issue by TingPing** [flatpak/freedesktop-sdk-images#100]
As of Nvidia 396 they have dropped 32bit installers. The 64bit one should still contain the runtime libs for 32bit compat though so we need to start extracting those.

In the mean time just to get 64bit out I just skipped the 32bit ones: https://github.com/flatpak/freedesktop-sdk-images/commit/ac89cbbcbf66d909566e29ea3cb85ca1377ececb

**Comment by lalbers** [comment]
@TingPing 
Just wanna say **Thank you!** for that fix
