### ISSUE TITLE
Zoom freezes

### ISSUE THREAD

**Issue by heftig** [flatpak/freedesktop-sdk-images#106]
us.zoom.Zoom frequently freezes on my machine (Arch Linux, Intel GPU, GNOME Wayland). Shortly after joining a call, all windows stop updating and can no longer be interacted with. Sound continues, though.

The official non-flatpak package from zoom.us runs fine.

I think this may be https://bugs.freedesktop.org/show_bug.cgi?id=106351 so https://patchwork.freedesktop.org/patch/223324/ (the final version of the patch from comment 13) needs to be applied. Arch's mesa already includes this patch.

**Comment by alexlarsson** [comment]
I had to revert that, as it didn't apply to our mesa version. Is there a backport of the patch?
