### ISSUE TITLE
Broken font configuration

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/freedesktop-sdk-images#108]
I noticed that color emoji not working for me. This is in the gnome master sdk:

$ fc-match emoji
DejaVuSans.ttf: "DejaVu Sans" "Book"

and this is on the host side:

$ fc-match emoji
NotoColorEmoji.ttf: "Noto Color Emoji" "Regular"

Looking into /etc/fonts/, I find:

$ ls -lL /etc/fonts/conf.d
ls: cannot access '/etc/fonts/conf.d/10-scale-bitmap-fonts.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/90-synthetic.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/49-sansserif.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/60-generic.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/51-local.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/65-fonts-persian.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/45-latin.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/50-user.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/20-unhint-small-dejavu-serif.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/30-metric-aliases.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/80-delicious.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/60-latin.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/20-unhint-small-vera.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/40-nonlatin.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/57-dejavu-serif.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/20-unhint-small-dejavu-sans-mono.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/69-unifont.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/65-nonlatin.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/20-unhint-small-dejavu-sans.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/57-dejavu-sans-mono.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/45-generic.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/57-dejavu-sans.conf': No such file or directory
ls: cannot access '/etc/fonts/conf.d/10-hinting-slight.conf': No such file or directory
total 80
l?????????  ? ?       ?         ?            ? 10-hinting-slight.conf
l?????????  ? ?       ?         ?            ? 10-scale-bitmap-fonts.conf
l?????????  ? ?       ?         ?            ? 20-unhint-small-dejavu-sans.conf
l?????????  ? ?       ?         ?            ? 20-unhint-small-dejavu-sans-mono.conf
l?????????  ? ?       ?         ?            ? 20-unhint-small-dejavu-serif.conf
l?????????  ? ?       ?         ?            ? 20-unhint-small-vera.conf
l?????????  ? ?       ?         ?            ? 30-metric-aliases.conf
-rw-r--r--  7 mclasen mclasen 440 Dec 31  1969 31-cantarell.conf
l?????????  ? ?       ?         ?            ? 40-nonlatin.conf
l?????????  ? ?       ?         ?            ? 45-generic.conf
l?????????  ? ?       ?         ?            ? 45-latin.conf
l?????????  ? ?       ?         ?            ? 49-sansserif.conf
-rw-r--r-- 14 mclasen mclasen 900 Dec 31  1969 50-flatpak.conf
l?????????  ? ?       ?         ?            ? 50-user.conf
l?????????  ? ?       ?         ?            ? 51-local.conf
l?????????  ? ?       ?         ?            ? 57-dejavu-sans.conf
l?????????  ? ?       ?         ?            ? 57-dejavu-sans-mono.conf
l?????????  ? ?       ?         ?            ? 57-dejavu-serif.conf
-rw-r--r-- 14 mclasen mclasen 482 Dec 31  1969 59-liberation-fonts-mono.conf
-rw-r--r-- 14 mclasen mclasen 344 Dec 31  1969 59-liberation-fonts-narrow.conf
-rw-r--r-- 14 mclasen mclasen 483 Dec 31  1969 59-liberation-fonts-sans.conf
-rw-r--r-- 14 mclasen mclasen 485 Dec 31  1969 59-liberation-fonts-serif.conf
l?????????  ? ?       ?         ?            ? 60-generic.conf
l?????????  ? ?       ?         ?            ? 60-latin.conf
l?????????  ? ?       ?         ?            ? 65-fonts-persian.conf
l?????????  ? ?       ?         ?            ? 65-nonlatin.conf
-rw-r--r-- 14 mclasen mclasen 334 Dec 31  1969 69-gnu-free-mono.conf
-rw-r--r-- 14 mclasen mclasen 979 Dec 31  1969 69-gnu-free-sans.conf
-rw-r--r-- 14 mclasen mclasen 972 Dec 31  1969 69-gnu-free-serif.conf
l?????????  ? ?       ?         ?            ? 69-unifont.conf
l?????????  ? ?       ?         ?            ? 80-delicious.conf
l?????????  ? ?       ?         ?            ? 90-synthetic.conf
-rwxr--r-- 14 mclasen mclasen 978 Dec 31  1969 README

So a lot of the conf.d symlinks are dangling, including the one that would set up emoji families (50-generic.conf)

**Comment by matthiasclasen** [comment]
I notice that these are now relative symlinks: ../../../share/fontconfig...
where the older freedesktop sdks used to have absolute symlinks to /usr/share/fontconfig...

**Comment by barthalion** [comment]
AFAIK it is based on freedesktop 1.8 so you should ask folks at #freedesktop-sdk or [on their gitlab](https://gitlab.com/freedesktop-sdk/freedesktop-sdk).

**Comment by Othko97** [comment]
We patched this issue in freedesktop 18.08, so gnome master should now work too.
