### ISSUE TITLE
org.freedesktop.Platform.GL.nvidia-390-48 not downloading, wrong url

### ISSUE THREAD

**Issue by kylemiller3** [flatpak/freedesktop-sdk-images#112]
```
Installing: org.freedesktop.Platform.GL.nvidia-390-48/x86_64/1.4 from flathub
[#=                  ] Downloading: 355.4 kB/46.7 MB (5.7 kB/s)    
Warning: Failed to install org.freedesktop.Platform.GL.nvidia-390-48/x86_64/1.4: While downloading http://http.download.nvidia.com/XFree86/Linux-x86_64/390.48/NVIDIA-Linux-x86_64-390.48-no-compat32.run: Socket I/O timed out

```

If I download from ```http://download.nvidia.com/XFree86/Linux-x86_64/390.48/NVIDIA-Linux-x86_64-390.48-no-compat32.run``` in my broswer I can get the file but ```http://http.download.nvidia.com/XFree86/Linux-x86_64/390.48/NVIDIA-Linux-x86_64-390.48-no-compat32.run``` appears to be the wrong url.

**Comment by benrob0329** [comment]
I'm getting the same thing for ``org.freedesktop.Platform.GL.nvidia-396-45/x86_64/1.4``

**Comment by TingPing** [comment]
It seems to be nvidias server having the problem. Nothing we can do about it.

**Comment by kylemiller3** [comment]
@TingPing can't the url just be changed to the one that works?

```http://download.nvidia.com/XFree86/Linux-x86_64/390.48/NVIDIA-Linux-x86_64-390.48-no-compat32.run```

if not why not?

**Comment by TingPing** [comment]
Ah, didn't see that a different URL worked.
