### ISSUE TITLE
Fonts installed in symbolic linked folder are lost in flatpak

### ISSUE THREAD

**Issue by Jehan** [flatpak/freedesktop-sdk-images#119]
Someone noticed that some fonts were missing in GIMP.
For instance on a Fedora, if you install the package `texlive-tex-gyre`, it would install a bunch of fonts under `/usr/share/texlive/texmf-dist/fonts/opentype/public/tex-gyre/` and add a symlink to this folder under `/usr/share/fonts/`.

Now I can note that the freedesktop runtime adds [/etc/fonts/conf.d/50-flatpak.conf](https://github.com/flatpak/freedesktop-sdk-images/blob/1.6/fontconfig-flatpak.conf) and in particular that `/run/host/fonts` is mapped to `/usr/share/fonts/`.
Unfortunately while doing so, it doesn't take into account symlinks which are not remapped. Hence any fonts which are installed as symlinks on the host system (such as this Tex Gyre package) are lost in the sandbox.

Of course, special-casing these would work, but this is obviously not very good. A generic solution is needed.
Could something be done about this?
Cf. https://github.com/flathub/org.gimp.GIMP/issues/20

**Comment by TingPing** [comment]
This is handled by Flatpak not the runtime: https://github.com/flatpak/flatpak

**Comment by Jehan** [comment]
Ok. New report: https://github.com/flatpak/flatpak/issues/2134
