### ISSUE TITLE
Add xdg-utils

### ISSUE THREAD

**Issue by cosimoc** [flatpak/freedesktop-sdk-images#12]
Especially now that xdg-utils supports flatpak natively, we should probably include them in the freedesktop/GNOME runtimes.
CC @mariospr

**Comment by alexlarsson** [comment]
Yeah, it makes a lot more sense now.

**Comment by mariospr** [comment]
Thanks for looping me in here @cosimoc. I'll try to resume the work from @mattdangerw and get the xdg-utils package added here, although it might take a while, as I never built a runtime before.

**Comment by hadess** [comment]
Please don't use Matt's fork, it's very very fragile. I'd rather you wrote compatible wrappers, that use GLib/GIO directly underneath, and which would work whether inside or outside the sandbox.

I'm all for adding those to the runtime though!

**Comment by cosimoc** [comment]
No need to use his fork -- Matt's patches are in git master.

**Comment by hadess** [comment]
I really don't want to see the original xdg-utils in the SDK. It really is utter garbage.

**Comment by mariospr** [comment]
We hold a discussion today during the hackfest and the agreement on this was to implement our own "thin" version of xdg-utils in that will provide a C implementation of xdg-open and xdg-email, which will rely on the OpenURI and Email portals respectively **and** that will wait for the reply from the portal frontend to arrive before dying, to prevent issues with D-Bus potentially dropping D-Bus messages if the caller dies too soon.

The new repository lives in https://github.com/flatpak/flatpak-xdg-utils, and would be pulled from the [freedesktop-sdk-images repo](https://github.com/flatpak/freedesktop-sdk-images) as soon as it's ready, hopefully removing the need from ever importing the shell-script based original xdg-utils package

**Comment by hadess** [comment]
Yay!

**Comment by mariospr** [comment]
...and it looks like @fmuellner has already come up with an implementation: https://github.com/fmuellner/flatpak-xdg-utils

**Comment by alexlarsson** [comment]
It's now at https://github.com/flatpak/flatpak-xdg-utils

**Comment by alexlarsson** [comment]
This is in 1.6 now
