### ISSUE TITLE
OpenCL is unavailable for Nvidia GL extension

### ISSUE THREAD

**Issue by gasinvein** [flatpak/freedesktop-sdk-images#124]
As I understand, a symlink `OpenCL` → `extra/OpenCL` should be present at the top directory of the extension, same as `vulkan` and `glvnd`.

**Comment by TingPing** [comment]
The symlink is made at the runtime level not by the extension so this is a problem for: https://gitlab.com/freedesktop-sdk/freedesktop-sdk

**Comment by gasinvein** [comment]
@TingPing 
>The symlink is made at the runtime level not by the extension

I was talking about exactly the extension's symlink.
https://github.com/flatpak/freedesktop-sdk-images/blob/589a96f2e399c54d4bef2b1105229bab65c3a382/nvidia-Makefile#L8-L10
Adding here a symilar symlink for OpenCL, like `ln -s extra/OpenCL ${FLATPAK_DEST}/OpenCL`, most likely will fix the issue (I tried adding this symlink under installed extension, that worked).

**Comment by TingPing** [comment]
I was just mistaken and have added it there already, sorry.

**Comment by gasinvein** [comment]
Didn't notice 2a7bc24. It should work, thanks.
