### ISSUE TITLE
The dbus_bus_get(DBUS_BUS_SYSTEM) aborts

### ISSUE THREAD

**Issue by xhorak** [flatpak/freedesktop-sdk-images#13]
In case the flatpacked application does not have access to system dbus (ie. does not have sockets=system-bus as accessible system resource), calling dbus_bus_get(DBUS_BUS_SYSTEM, nullptr) the program is aborted. 

Maybe that's actually desired effect, but in case of Firefox when user wants to use geolocation API the Firefox crashes (from dbus the list of wifi APs is requested). Is there any other way than sockets=system-bus to avoid this crash?

**Comment by alexlarsson** [comment]
I dunno why it crashed, but flatpak doesn't give you access to the system bus by default, you have to assign rights to some system bus name for it to be enabled.

For instance, in your case you need to add --system-talk-name=org.freedesktop.GeoClue2 to let it talk to geoclue.

**Comment by xhorak** [comment]
I'm afraid that Firefox is  not using GeoClue2, it's getting list of nearby APs from Network Manager and sending them to mozilla servers:
http://searchfox.org/mozilla-central/source/netwerk/wifi/nsWifiScannerDBus.cpp#32

**Comment by alexlarsson** [comment]
Well, whatever name it wants to access on the system bus, you need to ask for permission to do that.

**Comment by xhorak** [comment]
Sorry, this is not a bug of dbus. Mozilla code does not check for dbus_bus_get(DBUS_BUS_SYSTEM, nullptr) result, only asserting it won't return nullptr.
