### ISSUE TITLE
Request to import ibus 1.5.20 in org.freedesktop.Platform

### ISSUE THREAD

**Issue by fujiwarat** [flatpak/freedesktop-sdk-images#132]
Could you please import ibus 1.5.20 in org.freedesktop.[Platform|Sdk] ?

The IBus version includes the fixes to work with Atom and Slack applications:
https://github.com/ibus/ibus/commit/be7fb813e530442897a9f9130b8a26380e5a12a1
https://github.com/ibus/ibus/commit/60e246ef1593f599e2103070f8fa02649d60ada1

https://github.com/flatpak/flatpak/issues/1671

**Comment by refi64** [comment]
This repo was for the 1.6 Platform & Sdk, you want [the new repo on GitLab](https://gitlab.com/freedesktop-sdk/freedesktop-sdk).

**Comment by fujiwarat** [comment]
@kirbyfan64 
Thank you!
