### ISSUE TITLE
Will the patches be upstreamed?

### ISSUE THREAD

**Issue by probonopd** [flatpak/freedesktop-sdk-images#133]
Have/will the patches that make libraries relocatable be upstreamed, e.g., this one:
https://github.com/flatpak/freedesktop-sdk-images/blob/1.6/alsa-lib-plugin-path.patch?

I am also interested in getting ALSA relocatable and from a quick glance it seems that this patch is needed to get `ALSA_PLUGIN_DIR` to work.

Reference: https://github.com/mumble-voip/mumble/issues/3959#issuecomment-595894061

**Comment by TingPing** [comment]
This repo is dead.

If the patches still exist in https://gitlab.com/freedesktop-sdk/freedesktop-sdk then they are still relevant and you should discuss this with them.
