### ISSUE TITLE
Appstream metadata for "org.freedesktop.Platform.VAAPI.Intel" is unavailable

### ISSUE THREAD

**Issue by ghost** [flatpak/freedesktop-sdk-images#134]
It isn't possible to uninstall `org.freedesktop.Platform.VAAPI.Intel` using GNOME Software/KDE Discover because the appstream metadata doesn't seem to be present.

## Additional info
- Branches 21.08 and 22.08
- Fedora 37 Workstation

**Comment by TingPing** [comment]
This project is here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk
