### ISSUE TITLE
python3 is missing lib2to3

### ISSUE THREAD

**Issue by chergert** [flatpak/freedesktop-sdk-images#17]
Various python projects require this to translate python2 source to python3 when installing the package. The python2 runtime has this, but the python3 runtime seems to be missing it.

**Comment by alexlarsson** [comment]
Is it needed in the sdk or the platform?

**Comment by chergert** [comment]
I *think* SDK is fine since most things that use it are going to use it during the setup.py build phase.

**Comment by alexlarsson** [comment]
There seems to be two versions, python-2to3-2.7.12 and python3-2to3-3.5.2.
Should I add the python3 one?

**Comment by chergert** [comment]
Honestly, they are both probably needed.

**Comment by alexlarsson** [comment]
Ah, the python2 one is already there!

**Comment by alexlarsson** [comment]
Should be in 1.6/3.22 now.
