### ISSUE TITLE
cmake version

### ISSUE THREAD

**Issue by aleixpol** [flatpak/freedesktop-sdk-images#21]
At the moment we are offering 3.6.1 (even though 3.6.3 is available).

Having 3.7.2 (or 3.8.0) available would be very welcome as it has some features we use to properly integrate with IDE's (i.e. server mode).

**Comment by alexlarsson** [comment]
yocto master has 3.7.2. I'll try backporting that.

**Comment by alexlarsson** [comment]
Finishing building this, should be there in a bit.
