### ISSUE TITLE
Remove --disable* from ALSA lib build

### ISSUE THREAD

**Issue by MatMaul** [flatpak/freedesktop-sdk-images#28]
It seems that Qt framework is rebuilding ALSA lib because it needs some of the features disabled here. Any reason to keep them disabled ?

**Comment by alexlarsson** [comment]
Not really, which ones does it need?

**Comment by alexlarsson** [comment]
I mean, most of the features are not necessary useful in the container, since they rely on device access which might not be there...

**Comment by MatMaul** [comment]
I don't really know to be fair, they just don't disable anything. My guess would be instr and/or rawmidi and/or old-symbols however, since it seems to be sw code to generate sounds from sequences.

**Comment by alexlarsson** [comment]
But the qt build must check some features when it decides that it need to build alsa itself?

**Comment by MatMaul** [comment]
Ok so more infos : this is when compiling chromium for QtWebEngine, and it fails on snd_ctl_rawmidi_next_device so rawmidi should do the trick.

**Comment by adityashah1212** [comment]
It seems, openjdk also needs rawmidi. It throws "error: SND_RAWMIDI_STREAM_OUTPUT undefined."

**Comment by MatMaul** [comment]
Fixed.
