### ISSUE TITLE
OpenJdk extension

### ISSUE THREAD

**Issue by adityashah1212** [flatpak/freedesktop-sdk-images#30]
I wanted to add a jre extension to freedesktop platform and a jdk extension to freedesktop sdk. Though I am not sure if, they should be extensions or separate runtimes based on freedesktop runtime/sdk. Also as I mentioned in #28 ALSA's rawmidi support is needed to build OpenJdk8.

**Comment by Barthalion** [comment]
I don't think it makes much sense to have OpenJDK extension point as it should be possible to get it build in runtime/app instead.

**Comment by alexlarsson** [comment]
Yeah, i don't really think extensions should be used to recreate package dependencies. Also, jre:s are tricky things, apps often depend on a specific version.

**Comment by adityashah1212** [comment]
I understand, though we could still have java6, java7 and java8 as separate runtime right?

**Comment by Barthalion** [comment]
Maintaining a runtime is a huge commitment, pretty much synonymous with own distribution (slightly less if based on other runtime but still…). Something like a base app sounds better for this use case, if duplication is unwanted.

**Comment by alexlarsson** [comment]
That, or just shared Json. That is likely to be deduplicated anyway.

**Comment by adityashah1212** [comment]
Guy I was trying to compile openjdk, and realised that we need a boot-jdk. Compilation guide redirects to oracle jdk website. I think this might become a hindrance for application developers.

**Comment by adityashah1212** [comment]
I intend to work on this, this weekend... So what do you guys suggest, go with base app (which by my understanding would become an app on repo whose binaries would become a part of the developers app) or shared json.

Also there are a couple of concerns I have what about the security updates released by java with every uXXX version, how do we provide them? We can't have rebuilds every time a new uXXX comes out.

Also we have two use cases here
  (1) Applications like eclipse running on java, thus a core requirement
  (2) Applications like libreoffice which would only require java for plugins

**Comment by adityashah1212** [comment]
Hey guys, whenever I try to compile openjdk8 in snadbox it gives this error. Any ideas
`## Starting install
Installing jdk image into /app/lib/java/jvm/openjdk-1.8.0_141-flatpak
and creating 41 links from /app/lib/java/bin into the jdk.
/usr/bin/cp: failed to preserve ownership for /app/lib/java/jvm/openjdk-1.8.0_141-flatpak/jre/lib/amd64/server/libjsig.so: No such file or directory
make[1]: *** [BuildJdk.gmk:131: install] Error 1
make: *** [/run/build/openjdk8//make/Main.gmk:154: install-only] Error 2
Error: module openjdk8: Child process exited with code 2`

**Comment by alexlarsson** [comment]
@adityashah1212 That error should be fixed with ostree  2017.11  (it was due to https://github.com/ostreedev/ostree/pull/1137)

**Comment by alexlarsson** [comment]
@mrmcq2u Yeah, bundling an extensible thing like an IDE is complicated. The way e.g. gnome-builder does it is that the IDE itself uses flatpak to build in, so it doesn't need to have all the tools required for building things in its own bundles.

**Comment by adityashah1212** [comment]
Thanks @alexlarsson. As far as arm aarch64 are concerned we could use [AdoptJdk](https://adoptopenjdk.net) builds for bootjdk.

**Comment by alexlarsson** [comment]
@adityashah1212 That doesn't seem to have any 32bit builds (arm or intel)

**Comment by alexlarsson** [comment]
@adityashah1212 As for baseapp, the sdk extension i created at: https://gist.github.com/anonymous/c5a4780604949256c4ee146403f8826d has a `install.sh` script which bundles the jre in the app. All the app has to do is run this and set up the PATHs, then java in the bundled app should work. And since the copy is bitwise identical it will be shared between bundlers of it (that use the same extension build).

**Comment by adityashah1212** [comment]
> @adityashah1212 That doesn't seem to have any 32bit builds (arm or intel)

Yeah, I know... I was only talking about aarch64.

> So that baseapp can be used in case of simple applications based on only one runtime, while still having ability to use common modules if more jdk are needed.

What I meant here is, we should have both alternatives, so if in case an app needs multiple jre/jdk it have them by using one as baseapp and other from common modules

**Comment by alexlarsson** [comment]
@adityashah1212 A base app is essentially identical to copying the files from a sdk though, so if doing that is easy i see no reason to do the base-app version too.

**Comment by adityashah1212** [comment]
I understand that and agree with you, but what I am saying is we should have both prebuilt jdk and a json in common modules so the developer is able to choose multiple jdks in case of need.

**Comment by alexlarsson** [comment]
https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk9

**Comment by koppor** [comment]
Since Google leads to here when googling for flatpack jdk jre openjdk, here the most recent link (as of today):

SDK Extension for OpenJDK 11 --> https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11
