### ISSUE TITLE
Cursor theme

### ISSUE THREAD

**Issue by nedrichards** [flatpak/freedesktop-sdk-images#37]
It looks like the FDo runtime doesn't provide a cursor theme. Or if it does, it certainly doesn't have one with HiDPI assets as you can see from the following screenshots:

App using GNOME 3.24 Platform
![screenshot from 2017-09-05 21-17-49](https://user-images.githubusercontent.com/302677/30081597-b4832476-927f-11e7-92d3-5b4d2dc77024.png)

App using FDo 1.6 Platform
![screenshot from 2017-09-05 21-14-49](https://user-images.githubusercontent.com/302677/30081497-5d551b64-927f-11e7-809e-32d15847b6a8.png)

In either case this doesn't look particularly nice in apps.

**Comment by nedrichards** [comment]
@cosimoc did some debugging here. Looks like the HiDPI issue is because libXcursor doesn't look in the /app prefix.

**Comment by cosimoc** [comment]
Yeah, I will post a patch shortly.

**Comment by cosimoc** [comment]
https://github.com/flatpak/freedesktop-sdk-images/pull/39

**Comment by nedrichards** [comment]
Resolved!
