### ISSUE TITLE
Nvidia-384-90 drivers

### ISSUE THREAD

**Issue by hubslave** [flatpak/freedesktop-sdk-images#42]
Hello, Nvidia 384-90 drivers are already out and without their flatpak nvidia runtime counterpart some flatpak applications don't seem to work :(

For example GnomeMpv have these problems:
```
$ flatpak run io.github.GnomeMpv
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libEGL warning: DRI2: failed to authenticate
: CommandLine Error: Option 'bb-vectorize-ignore-target-info' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

( https://github.com/gnome-mpv/gnome-mpv/issues/310 )

If you need any more information or testing please let me know,
Have a nice day :)

**Comment by hubslave** [comment]
@alexlarsson please do we have some news on this issue? If new nvidia runtime needs testing before release I'd be happy to do it :)

**Comment by TingPing** [comment]
```
08:03:34| <TingPing> alexlarsson, did nvidia-384-90 never get sync'd to flathub?
08:04:09| <alexlarsson> probably not...
08:04:36| <alexlarsson> I want to sync, but not until the arm story is ok
```

**Comment by hubslave** [comment]
Thank you very much for response @TingPing. But what is the "arm story"?

**Comment by TingPing** [comment]
They are just working on various fixes for the runtime on arm.

**Comment by hubslave** [comment]
Thank you very much for information. I'm sorry for too much questions, but when talking about ARM - at the moment there are 2 packages for NVidia runtimes - org.freedesktop.Platform.GL32.nvidia and org.freedesktop.Platform.GL.nvidia. Is one of them responsible for ARM runtimes or will there be also the third package for ARM architecture, for example "org.freedesktop.Platform.GLARM.nvidia" ?

**Comment by hubslave** [comment]
And I was also wondering - when there are new updates for nvidia runtimes on flathub, flatpak update usually downloads them and everything is working fine but the old ones are still present on my system. (flatpak does not replace or uninstall these old packages). Is it safe to uninstall old runtimes and leave just the newest one present?

**Comment by TingPing** [comment]
The 32 one is for 32bit applications in 64bit runtimes.

**Comment by TingPing** [comment]
> Is it safe to uninstall old runtimes and leave just the newest one present?

Yes.

**Comment by hubslave** [comment]
> The 32 one is for 32bit applications in 64bit runtimes.

And the other one is for 64bit runtimes? I mean if there is no package for ARM runtimes out yet, can't you release nvidia-384-90 runtime at least for 32 a 64 bit platforms for now? And release the ARM package when it will be fixed and ready?

Sorry for being troublesome but I really miss Gnome MPV :)

**Comment by TingPing** [comment]
The problem isn't Nvidia on ARM, the entire ARM runtime is being worked on.

**Comment by hubslave** [comment]
But why do 32 and 64 bit platforms have to wait for ARM runtime being finished? Can't they receive updates in the meantime? I mean I am really happy to hear that flatpaks are going to support ARM architecture but would it be a big problem to release nvidia-384-90 runtime for 32 and 64 bit platforms to make software which is broken because of incompatibility of current flatpak runtime and current nvidia drivers function again?

**Comment by hubslave** [comment]
Please don't get me wrong, I really really like flatpaks and I wish they would become as widely used as possible but in current state multiple applications are unusable which could hurt flatpak reputation in general

**Comment by hubslave** [comment]
@TingPing @alexlarsson thank you very much for latest NVidia runtime update, flatpaks are running as charm again :)
