### ISSUE TITLE
libmount present in Sdk but not in org.gnome.Platform runtime

### ISSUE THREAD

**Issue by mariospr** [flatpak/freedesktop-sdk-images#5]
Apparently, the org.gnome.Platform flatpak does not contain libmount (e.g. no /lib/libmount.so\* files) while the org.gnome.Sdk does, which is causing quite some trouble with any flatpak built after the patches for bug 522053 landed in master:

As the Sdk contains libmount's files Glib is compiled with libmount support linking against the relevant files, but as those files are not in the Platform runtime, any flatpak built from that point on will fail with something like this:

```
$ flatpak run org.gnome.PortalTest
portal-test: error while loading shared libraries: libmount.so.1: cannot open shared object file: No such file or directory
```

@ebassi has looked a bit into why this could be happening and it seems the issue could be somewhere in the recipes of the freedesktop.org Yocto base but, as it seems like Alex Larsson would be the best person anyway to check this, we temporarily disabled libmount support on Glib in the meantime, as a temporary measure so that flatpaks built will work fine back again: https://bugzilla.gnome.org/show_bug.cgi?id=769284

Ideally, we would re-enable libmount support in glib once this is fixed, so I'll file a new bug in there now to keep track of that

**Comment by mariospr** [comment]
Relevant bug to restore libmount support: https://bugzilla.gnome.org/show_bug.cgi?id=769629

**Comment by ebassi** [comment]
The relevant Yocto package to add to the [platform task](https://cgit.freedesktop.org/xdg-app/freedesktop-sdk-base/tree/meta-freedesktop/recipes-core/tasks/task-freedesktop-contents-platform.bb) is `util-linux-libmount`; currently it's likely being brought into the SDK via dependencies — though I cannot say how.

**Comment by mariospr** [comment]
Seems like this was actually fixed by @matthiasclasen some days ago, and libmount is now showing up on the org.gnome.Platform runtime for the 3.20 branch: https://github.com/flatpak/freedesktop-sdk-base/commit/5cf4be34b16107eb0c44d061868d6837de81a591.

Unfortunately, the master branch has not been building for a while (due to [this bug](https://bugzilla.gnome.org/show_bug.cgi?id=768088)) and libmount is not yet available in the last version available for that branch, so I'd rather keep this issue open in the meanwhile, so that we restore libmount support in GLib once it's completely fixed and this issue can be closed.
