### ISSUE TITLE
Build gst-plugins-bad with ladspa plugin support

### ISSUE THREAD

**Issue by AsavarTzeth** [flatpak/freedesktop-sdk-images#50]
I maintain [com.github.wwmm.pulseeffects](https://github.com/flathub/com.github.wwmm.pulseeffects), which makes use of gstreamer and ladspa plugins. Currently I am trying to migrate to 3.26, and I want to make use of the included gstreamer version (1.12.x) included in the sdk.

However a lack of ladspa plugin support in gst-plugins bad is preventing this. Adding the [ladspa-sdk](http://www.ladspa.org/ladspa_sdk/overview.html) should solve this. You can find my current module [here](https://github.com/flathub/com.github.wwmm.pulseeffects/blob/master/com.github.wwmm.pulseeffects.json#L117).

I have had some issues with the official source though. On occasion it appears the archive [ladspa_sdk_1.13.tgz](http://www.ladspa.org/download/ladspa_sdk_1.13.tgz) is updated in place, without warning. This is obviously not ideal, especially from a security point of view.

Some distributions workaround this by using other sources. For example, the Arch Linux package uses:
https://github.com/OpenMandrivaAssociation/ladspa/blob/master/ladspa_sdk_1.13.tgz

**Comment by TingPing** [comment]
You can build and use your own gstreamer plugins they don't necessarily need to be in the sdk.

**Comment by TingPing** [comment]
Here is an example: https://github.com/flathub/io.github.Pithos/blob/master/io.github.Pithos.json#L41-L72

**Comment by AsavarTzeth** [comment]
Well as I understand it ladspa plugins actually are not gstreamer plugins, but they work thanks to a bridge in gst-plugins-bad. However this bridge requires the ladspa SDK.

**Comment by TingPing** [comment]
Well you can replace the core components of `gst-plugins-bad` even if they aren't plugins, just a bit more annoying.

**Comment by AsavarTzeth** [comment]
Well it seems you were right from the beginning. The ladspa plugin bridge is just another plugin installed as `libgstladspa.so`. I managed to build only this plugin, install it and now the app now finds the plugin without any complications or any other gstreamer related modules required.

The bad news is that the `meson.build` file in the `ext` subdir does not support ladspa yet (it is commented). So I have to use autotools, but since I also cannot find any `--disable-all` option, that means a lot of config lines (83 at this moment). But at least it works.

**Comment by TingPing** [comment]
@AsavarTzeth Yea the gstreamer build files are the worst...

Looks like it should be trivial to port the ladspa checks to meson though: https://github.com/GStreamer/gst-plugins-bad/blob/master/configure.ac#L2471-L2481

**Comment by AsavarTzeth** [comment]
Interesting, I might look into that. But that will have to be a project for another day.

Thanks for the great help, as usual. Closing, since I now know the better way to do it.
